name: PTT Crawler

on:
  schedule:
  - cron: '0 4 * * *'  # UTC 04:00
  - cron: '0 10 * * *' # UTC 10:00
  workflow_dispatch:  # 允許手動觸發

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run crawler
      env:
        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      run: python ptt_crawler_online.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')" || echo "沒有更改需要提交"
        git push
        
    - name: Clean old data # 刪除 30 天前的 JSON 檔案
      run: |
        find ./ptt_drama_ticket_data -name "ptt_Drama-Ticket_gracie_*.json" -type f -mtime +30 -delete
    
    - name: Send failure notification
      if: failure()
      run: |
        curl -X POST https://api.line.me/v2/bot/message/push \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.LINE_TOKEN }}" \
        -d '{
          "to": "${{ secrets.LINE_USER_ID }}",
          "messages": [{"type": "text", "text": "爬蟲執行失敗，請檢查 GitHub Actions 日誌"}]
        }'
